CREATE OR REPLACE TABLE da304.Web_site(
web_site_sk INT64,
web_site_id STRING,
web_rec_start_date DATE,
web_rec_end_date DATE,
web_name STRING,
web_open_date_sk INT64,
web_close_date_sk INT64,
web_class STRING,
web_manager STRING,
web_mkt_id INT64,
web_mkt_class STRING,
web_mkt_desc STRING,
web_market_manager STRING,
web_company_id INT64,
web_company_name STRING,
web_street_number STRING,
web_street_name STRING,
web_street_type STRING,
web_suite_number STRING,
web_city STRING,
web_county STRING,
web_state STRING,
web_zip STRING,
web_country STRING,
web_gmt_offset FLOAT64,
web_tax_percentage FLOAT64
)
